class_name ShootBullet
extends Area3D
## A projectile. The whole point of this probe is that it is a SEPARATE SCENE
## FILE, stamped out at runtime — the first thing in this project that did not
## exist when the level loaded.
##
## Two things about that are worth having in your hands before anything else:
##
## 1. A fresh instance knows nothing. Everything it needs is written into it by
##    whoever fired it, in the handful of lines right after instantiate() —
##    see ShootPlayer._fire(). That handshake is the whole of "configuring a
##    prefab" in Godot.
## 2. It has to be added to the WORLD, not to the shooter. Add it under the
##    player and it inherits his transform: the bullet would politely follow
##    him around while pretending to fly. The player owns nothing it fires.
##
## Note there is not one @export in this file. This scene answers "what IS a
## bullet" — a sphere, a shape, a three-second lifetime. Every NUMBER lives on
## the gun, because how fast and how hard it hits is a fact about the weapon
## firing today, not about bullets in general. One place to look, and it stays
## on a node that does not vanish while you are reaching for it.

## Metres per second. Set by the gun before the bullet enters the tree.
var speed := 25.0

## Push given to anything with mass that gets hit.
var punch := 6.0

## How the bullet notices it hit something.
##
## true  — sweep the segment the bullet is about to travel and stop at the
##         first thing on it. One raycast per bullet per tick, and it cannot
##         miss however fast the bullet goes. The right answer for anything
##         that moves faster than it is wide.
## false — trust the Area3D to report whatever it happens to be overlapping at
##         the end of each physics step. Cheaper, and it lies in two different
##         ways, both worth meeting in person:
##
##         · at speed it tunnels. Measured in this level: at 150 m/s a bullet
##           covers 2.5 m per tick, and with sweep off not one of fifteen shots
##           hit anything at all — they flew through the panel, the boxes and
##           the far wall and died of old age. With sweep on, at the same speed
##           and at 300, every one of them died on the first thing it met.
##         · it is blind to collision generated by CSG. `use_collision` on a
##           CSGBox3D builds a body straight in the physics server, and no node
##           is attached to it, so body_entered can never fire for it. A
##           CharacterBody3D walks into that collision perfectly well — which
##           is exactly why probes 01 and 02 never noticed. Level geometry that
##           has to be SHOT needs a real StaticBody3D, which is why the
##           blockout here carries one under every wall.
var sweep := true

## How much of the shooter's own motion the bullet carries away with it.
##
## 0 — the bullet leaves as if fired from a tripod. Strafe while holding the
##     trigger and the stream visibly hinges: every bullet flies dead straight,
##     but each one starts further sideways than the last, so the line of them
##     bends away behind you. Quake does this, and it is what makes leading a
##     moving target a skill rather than an accident.
## 1 — the bullet keeps your sideways speed, so the stream stays square in
##     front of you no matter how you strafe. What a real gun does, and what
##     most modern shooters copy.
var inherit_shooter_velocity := 0.0

var _dir := Vector3.FORWARD
## The shooter's motion, already scaled by inherit_shooter_velocity.
var _carried := Vector3.ZERO
var _shooter: Node3D


## Called by the gun once the numbers above have been written in, and before
## the bullet enters the tree.
func setup(direction: Vector3, shooter: Node3D) -> void:
	_dir = direction.normalized()
	_shooter = shooter
	if inherit_shooter_velocity > 0.0 and shooter is CharacterBody3D:
		_carried = shooter.velocity * inherit_shooter_velocity


func _physics_process(delta: float) -> void:
	var step := (_dir * speed + _carried) * delta
	if sweep and _sweep_hit(step):
		return
	global_position += step


## Look along the step before taking it. Returns true if the bullet died here.
func _sweep_hit(step: Vector3) -> bool:
	var from := global_position
	var q := PhysicsRayQueryParameters3D.create(from, from + step)
	q.exclude = [_shooter.get_rid()] if _shooter is CollisionObject3D else []
	# Areas are not solid; only bodies stop a bullet.
	q.collide_with_areas = false
	var hit := get_world_3d().direct_space_state.intersect_ray(q)
	if hit.is_empty():
		return false
	global_position = hit.position
	_resolve(hit.collider)
	return true


## Wired in Bullet.tscn to the Area3D's own body_entered signal.
func _on_body_entered(body: Node3D) -> void:
	if sweep:
		return  # the sweep already owns hit detection; do not report twice
	_resolve(body)


func _resolve(body: Node) -> void:
	if body == _shooter:
		return
	if body is RigidBody3D:
		# The only thing that separates a target from scenery: it has mass, so
		# it can be told about the hit in the only language physics speaks.
		body.apply_impulse((_dir * speed + _carried).normalized() * punch,
			global_position - body.global_position)
	if _shooter and _shooter.has_method(&"register_hit"):
		_shooter.register_hit(body, global_position)
	queue_free()
